/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCesium: typeof import('./../components/map/BaseCesium.vue')['default']
    BaseChart: typeof import('./../components/charts/BaseChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenFooter: typeof import('./../components/screen/ScreenFooter.vue')['default']
    ScreenHeader: typeof import('./../components/screen/ScreenHeader.vue')['default']
    ScreenLayout: typeof import('./../components/screen/ScreenLayout.vue')['default']
    ScreenPanel: typeof import('./../components/screen/ScreenPanel.vue')['default']
  }
}
