/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminPlaceholder: typeof import('./../components/admin/AdminPlaceholder.vue')['default']
    BaseCesium: typeof import('./../components/baseCesium/BaseCesium.vue')['default']
    BaseChart: typeof import('./../components/charts/BaseChart.vue')['default']
    BaseList: typeof import('./../components/admin/baseList.vue')['default']
    BaseMenu: typeof import('./../components/baseUi/BaseMenu.vue')['default']
    BaseMenuHorizontalAside: typeof import('./../components/baseMenuHorizontal/baseMenuHorizontalAside.vue')['default']
    BaseMenuHorizontalHeader: typeof import('./../components/baseMenuHorizontal/baseMenuHorizontalHeader.vue')['default']
    BasePagination: typeof import('./../components/base-pagination/base-pagination.vue')['default']
    BasePanel: typeof import('./../components/basePanel/basePanel.vue')['default']
    BasePopover: typeof import('./../components/basePopover/basePopover.vue')['default']
    BaseTab: typeof import('./../components/baseTab/baseTab.vue')['default']
    BaseTable: typeof import('./../components/baseTable/baseTable.vue')['default']
    BaseTableList: typeof import('./../components/admin/baseTableList.vue')['default']
    BaseTableV2: typeof import('./../components/base-table/base-table-v2.vue')['default']
    BaseTitle: typeof import('./../components/admin/baseTitle.vue')['default']
    BaseTitle2Panel: typeof import('./../components/admin/baseTitle2Panel.vue')['default']
    BaseTree: typeof import('./../components/baseUi/BaseTree.vue')['default']
    ConfirmBox: typeof import('./../components/baseMessageBox/confirmBox.vue')['default']
    copy: typeof import('./../components/admin/baseTitle copy.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    LayerControlPanel: typeof import('./../components/layerControl/LayerControlPanel.vue')['default']
    MapPopupPanel: typeof import('./../components/basePanel/MapPopupPanel.vue')['default']
    PopupInfo: typeof import('./../components/basePanel/PopupInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScreenFooter: typeof import('./../components/screen/ScreenFooter.vue')['default']
    ScreenHeader: typeof import('./../components/screen/ScreenHeader.vue')['default']
    ScreenLayout: typeof import('./../components/screen/ScreenLayout.vue')['default']
    ScreenPanel: typeof import('./../components/screen/ScreenPanel.vue')['default']
  }
}
